### ISSUE TITLE
host_vars file with uppercase chars

### ISSUE THREAD

**Issue by EdificomSA** [carlmontanari/nornir_ansible#128]
In the hosts (ini) file, I have some hosts using uppercase naming and in the host_vars folder the filename are also uppercase
With Nornir, all hosts are lowercase (I think by design)
Unfortunately it does not work with the way the inventory plugin parses Ansible inventory and host_vars (#3)
I haven't found where the host name goes lowercase (ConfigParser maybe ?)

https://github.com/carlmontanari/nornir_ansible/blob/03f7f64e2c47398dc425a2e9433d2eca120ff79c/nornir_ansible/plugins/inventory/ansible.py#L129

I'll do some tests and maybe write a PR when I got time

**Comment by carlmontanari** [comment]
sweet, thanks! will follow up in the pr!
