### ISSUE TITLE
Normalize inventory when not using ansible_host

### ISSUE THREAD

**Issue by Shourai** [carlmontanari/nornir_ansible#47]
Sometimes I use only ip addresses in my inventory file, without the alias and `ansible_host=` variable.
This speeds up things considerably as you can just plop a range of ip addresses where a certain task needs to be run.
e.g.:
```
[Cisco]
172.16.1.1
172.16.1.2
172.16.1.3
172.16.1.4
172.16.1.5
...
```
However during normalization of ini files it expects the hostname and `ansible_host=`.
I am wondering what your thoughts are to adding such functionality?

**Comment by carlmontanari** [comment]
Hey @Shourai -- definitely open for a pr for this. I probably wont implement this myself anytime soon, but am more than happy to review pr and get it merged as this seems like a good addition. Obviously we would just need to ensure we dont break any existing functionality!

**Comment by Shourai** [comment]
I opened a PR for this, however the tests of this repository were giving some issues.
To fix that I opened another PR:https://github.com/carlmontanari/nornir_ansible/pull/48

**Comment by Shourai** [comment]
Hey @carlmontanari,

1.  You are absolutely right that it should also apply to yaml inventory. I hardly use the yaml style inventory for ansible as I find the ini format easier when targetting many devices.
2. That is another oversight on my part, since `ansible_host` is not defined it should actually use `two.example.com` as hostname. However when I run the test it seems to fail there. Don't know why yet as I will have to dive into the code some more.

I really like how clean your solution is!
Unfortunately the tests are failing, instead of expecting hostnames it not expects `null`
Thank you so much for picking this up.

**Comment by carlmontanari** [comment]
> Unfortunately the tests are failing, instead of expecting hostnames it not expects null

I think this is working as it should in my PR, but if there is something incorrect there let me know. If you think my PR is good to go we can go ahead and get it merged to develop and close out the other ones. Let me know if I'm missing anything though or of if we should try to fix things in a different way.

Once we get whatever merged I will probably make the next release of this on 2021.07.30 so it will be available on PyPI at that point.

Carl

**Comment by Shourai** [comment]
Hey @carlmontanari,

My apologies, it seems vscode is acting which causes pytest to not work due to pythonpath issues.
Running the tests in terminal with  `python -m pytest` works!
Your code looks good, thanks!

**Comment by carlmontanari** [comment]
Cool, thanks for clearing that up! Appreciate your help on this! I'll get that merged to develop shortly!

Carl
