### ISSUE TITLE
Support For Ansible Patterns

### ISSUE THREAD

**Issue by sjtarik** [carlmontanari/nornir_ansible#5]
Hey Folks, 

I am looking for comments on introducing [Ansible-like](https://docs.ansible.com/ansible/latest/user_guide/intro_patterns.html) patterns for Nornir. 
 
I really like filters and functions in Nornir but I have lots of Ansible automation/playbooks/integrations and it is really convenient to pass a Ansible pattern to filter groups/hosts especially for Slack integrations or scripts asking for input. 

Previous discussion on [Nornir](https://github.com/nornir-automation/nornir/issues/575) 

Thanks,
Tarik

**Comment by carlmontanari** [comment]
Hi Tarik,

If you are interested in working on a PR for adding this that'd be fine by me so long as none of the "normal" behavior of nornir/the inventory plugin are modified. You can also check out [nornsible](https://github.com/carlmontanari/nornsible)... at this point its lagging behind a bit but already does *some* (definitely not all) of what it looks like you are after... also it does require a bit of different setup for things, but could be helpful for a starting point and/or some ideas. 

Carl

**Comment by sjtarik** [comment]
Awesome. Thanks for implementing Ansible Inventory too. I think after my PTO I would send the first PR as an Ansible Filter to Ansible Inventory repo first. That would also cover some todo items in nornsible it seems.

**Comment by carlmontanari** [comment]
Sounds good, enjoy PTO :D! Oh -- typo above:

` "normal" behavior of nornir/the inventory plugin are modified.`

Should be:

` "normal" behavior of nornir/the inventory plugin are NOT modified.`

Basically I would just view this as another tool/widget that you can import/call against inventory. Probably that was obvious but just saw what I wrote and was like "that doesn't look right" :D

**Comment by carlmontanari** [comment]
@sjtarik I'm going to close this for now, but you are more than welcome to open a PR for this and we can get it sorted out!
