### ISSUE TITLE
Accessing Group Vars for ansible Inventory

### ISSUE THREAD

**Issue by parth995** [carlmontanari/nornir_ansible#57]
Hi Team,

I see a bug or challenge may be to access a group vars/items in nornir script when we use ansible as a inventory plugin.

**Below thing works :-**
nr.inventory.hosts['<host_name>'].items()

**Below one Doesn't works :-**
nr.inventory.groups['<group_name>'].items()

**Versions of package used :-**
netmiko==3.4.0
nornir==3.1.1
nornir-ansible==2020.9.26
nornir-napalm==0.1.2
nornir-scrapli==2021.1.30
nornir-utils==0.1.2
Python 3.9.5

Any help would be appreciated. Thanks

**Comment by parth995** [comment]
Ref :- https://github.com/nornir-automation/nornir/issues/701

**Comment by carlmontanari** [comment]
> that said, even if this issue was opened there, provided details are not enough to assist you. at the minimum, there needs to be minimal reproduction which demonstrates the problem together with versions of python/nornir/plugin.

If you think there is a bug and want to open a PR I'll review, but without a reproducible example/setup I'm going to close this. Feel free to reopen with a reproducible example and I'll try to take a look at some point.

**Comment by parth995** [comment]
I have already added a example which works and which doesn't works

**Comment by parth995** [comment]
**Config.yaml file** 
inventory:
  plugin: AnsibleInventory
  options:
    hostsfile: "inventory/inventory.yaml"

runner:
  plugin: threaded
  options:
    num_workers: 10

**defaults.yaml** 
platform: "ios"
connection_options:
  scrapli:
    extras:
      auth_strict_key: False
